title: afraid
author: llccing
email: lcf33123@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  do what you want to do, think what you want to think

# social links
twitter_username: llccing
github_username:  llccing

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
